/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as PmlMdaIndexImport } from './routes/pml-mda/index'
import { Route as DemandaIndexImport } from './routes/demanda/index'
import { Route as DemandaBalanceIndexImport } from './routes/demanda-balance/index'
import { Route as CapacidadTransferenciaIndexImport } from './routes/capacidad-transferencia/index'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PmlMdaIndexRoute = PmlMdaIndexImport.update({
  id: '/pml-mda/',
  path: '/pml-mda/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/pml-mda/index.lazy').then((d) => d.Route))

const DemandaIndexRoute = DemandaIndexImport.update({
  id: '/demanda/',
  path: '/demanda/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/demanda/index.lazy').then((d) => d.Route))

const DemandaBalanceIndexRoute = DemandaBalanceIndexImport.update({
  id: '/demanda-balance/',
  path: '/demanda-balance/',
  getParentRoute: () => rootRoute,
} as any)

const CapacidadTransferenciaIndexRoute =
  CapacidadTransferenciaIndexImport.update({
    id: '/capacidad-transferencia/',
    path: '/capacidad-transferencia/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/capacidad-transferencia/': {
      id: '/capacidad-transferencia/'
      path: '/capacidad-transferencia'
      fullPath: '/capacidad-transferencia'
      preLoaderRoute: typeof CapacidadTransferenciaIndexImport
      parentRoute: typeof rootRoute
    }
    '/demanda-balance/': {
      id: '/demanda-balance/'
      path: '/demanda-balance'
      fullPath: '/demanda-balance'
      preLoaderRoute: typeof DemandaBalanceIndexImport
      parentRoute: typeof rootRoute
    }
    '/demanda/': {
      id: '/demanda/'
      path: '/demanda'
      fullPath: '/demanda'
      preLoaderRoute: typeof DemandaIndexImport
      parentRoute: typeof rootRoute
    }
    '/pml-mda/': {
      id: '/pml-mda/'
      path: '/pml-mda'
      fullPath: '/pml-mda'
      preLoaderRoute: typeof PmlMdaIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/capacidad-transferencia': typeof CapacidadTransferenciaIndexRoute
  '/demanda-balance': typeof DemandaBalanceIndexRoute
  '/demanda': typeof DemandaIndexRoute
  '/pml-mda': typeof PmlMdaIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/capacidad-transferencia': typeof CapacidadTransferenciaIndexRoute
  '/demanda-balance': typeof DemandaBalanceIndexRoute
  '/demanda': typeof DemandaIndexRoute
  '/pml-mda': typeof PmlMdaIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/capacidad-transferencia/': typeof CapacidadTransferenciaIndexRoute
  '/demanda-balance/': typeof DemandaBalanceIndexRoute
  '/demanda/': typeof DemandaIndexRoute
  '/pml-mda/': typeof PmlMdaIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/capacidad-transferencia'
    | '/demanda-balance'
    | '/demanda'
    | '/pml-mda'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/capacidad-transferencia'
    | '/demanda-balance'
    | '/demanda'
    | '/pml-mda'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/capacidad-transferencia/'
    | '/demanda-balance/'
    | '/demanda/'
    | '/pml-mda/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CapacidadTransferenciaIndexRoute: typeof CapacidadTransferenciaIndexRoute
  DemandaBalanceIndexRoute: typeof DemandaBalanceIndexRoute
  DemandaIndexRoute: typeof DemandaIndexRoute
  PmlMdaIndexRoute: typeof PmlMdaIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CapacidadTransferenciaIndexRoute: CapacidadTransferenciaIndexRoute,
  DemandaBalanceIndexRoute: DemandaBalanceIndexRoute,
  DemandaIndexRoute: DemandaIndexRoute,
  PmlMdaIndexRoute: PmlMdaIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/capacidad-transferencia/",
        "/demanda-balance/",
        "/demanda/",
        "/pml-mda/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/capacidad-transferencia/": {
      "filePath": "capacidad-transferencia/index.tsx"
    },
    "/demanda-balance/": {
      "filePath": "demanda-balance/index.tsx"
    },
    "/demanda/": {
      "filePath": "demanda/index.tsx"
    },
    "/pml-mda/": {
      "filePath": "pml-mda/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
